/* 
 * Copyright (c) 2014 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc2084.CMonster2014.commands;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2084.CMonster2014.Robot;

/**
 * Command that drives in arcade drive mode. This is only used if our gyro fails
 * and we have to revert to this during a match.
 *
 * @author Ben Wolsieffer
 */
public class DriveCommand extends Command {

    public DriveCommand() {
        // This command drives, so it requires the drive subsystem.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveSubsystem);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    /**
     * Does nothing.
     */
    protected void initialize() {
    }

    /**
     * Updates the robot speed and rotation based on the values of the drive
     * joystick.
     */
    protected void execute() {
        Joystick j = Robot.oi.getDriveJoystick();
        Robot.driveSubsystem.getRobotDrive().arcadeDrive(j.getY(), j.getX());
    }

    /**
     * This command never ends on its own but it could be interrupted.
     *
     * @return false
     */
    protected boolean isFinished() {
        return false;
    }

    /**
     * Stops the drive motors.
     */
    protected void end() {
        Robot.driveSubsystem.getRobotDrive().stopMotor();
    }

    /**
     * Stops the drive motors.
     */
    protected void interrupted() {
        end();
    }
}
