/* 
 * Copyright (c) 2016 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc.team2084.CMonster2016.commands;

import java.util.function.DoubleSupplier;

import org.usfirst.frc.team2084.CMonster2016.Robot;
import org.usfirst.frc.team2084.CMonster2016.RobotMap;
import org.usfirst.frc.team2084.CMonster2016.drive.GyroArcadeDriveAlgorithm;

/**
 * Rotates the robot to the specified heading.
 */
public class RotateToHeading extends ParameterCommand {

    private static final String HEADING_KEY = "Heading";

    protected double heading;
    private DoubleSupplier headingSupplier;
    private final GyroArcadeDriveAlgorithm arcadeDrive = RobotMap.driveSubsystemArcadeDriveAlgorithm;

    public RotateToHeading(DoubleSupplier heading) {
        headingSupplier = heading;
        init();
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public RotateToHeading(double heading) {
        addNumberParameter(HEADING_KEY, heading);
        headingSupplier = () -> getNumberParameter(HEADING_KEY);

        init();

    }

    private void init() {
        requires(Robot.driveSubsystem);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        heading = headingSupplier.getAsDouble();
        arcadeDrive.rotateTo(heading);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        arcadeDrive.rotateTo(heading);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return arcadeDrive.isHeadingOnTarget() || isTimedOut();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        RobotMap.driveSubsystemArcadeDriveAlgorithm.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
