/* 
 * Copyright (c) 2016 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc.team2084.CMonster2016.commands;

import java.util.function.DoubleSupplier;

import org.usfirst.frc.team2084.CMonster2016.Robot;
import org.usfirst.frc.team2084.CMonster2016.RobotMap;
import org.usfirst.frc.team2084.CMonster2016.drive.GyroArcadeDriveAlgorithm;

/**
 * Rotates the robot to the specified heading. This command ends when the
 * rotation has been completed. Sometimes, the end condition is not triggered,
 * because PID controllers are hard to tune effectively.
 */
public class RotateToHeading extends ParameterCommand {

    private static final String HEADING_KEY = "Heading";

    protected DoubleSupplier headingSupplier;
    private final GyroArcadeDriveAlgorithm arcadeDrive = RobotMap.driveSubsystemArcadeDriveAlgorithm;

    public RotateToHeading(DoubleSupplier heading) {
        headingSupplier = heading;
        init();
    }

    public RotateToHeading(DoubleSupplier heading, double timeout) {
        headingSupplier = heading;
        setTimeout(timeout);
        init();
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public RotateToHeading(double heading, double timeout) {
        addNumberParameter(HEADING_KEY, heading);
        headingSupplier = () -> getNumberParameter(HEADING_KEY);

        setTimeout(timeout);

        init();

    }

    private void init() {
        requires(Robot.driveSubsystem);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        execute();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        arcadeDrive.rotateTo(headingSupplier.getAsDouble());
    }

    /**
     * @return true when the heading is on target, the command times out, or the
     *         navX disconnects
     */
    @Override
    protected boolean isFinished() {
        return arcadeDrive.isHeadingOnTarget() || isTimedOut()
                || /* If we lose the gyro, stop */!RobotMap.driveSubsystemNavX.isConnected();
    }

    /**
     * Stops the drive train.
     */
    @Override
    protected void end() {
        RobotMap.driveSubsystemArcadeDriveAlgorithm.stop();
    }

    @Override
    protected void interrupted() {
        end();
    }
}
