/* 
 * Copyright (c) 2014 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc2084.CMonster2014.subsystems;

import org.usfirst.frc2084.CMonster2014.RobotMap;
import org.usfirst.frc2084.CMonster2014.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class DriveSubsystem extends Subsystem {

    public static final double CRAB_SPEED = 0.6;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController frontLeftJaguar = RobotMap.driveSubsystemFrontLeftJaguar;
    SpeedController frontRightJaguar = RobotMap.driveSubsystemFrontRightJaguar;
    SpeedController rearLeftJaguar = RobotMap.driveSubsystemRearLeftJaguar;
    SpeedController rearRightJaguar = RobotMap.driveSubsystemRearRightJaguar;
    Encoder rearRightEncoder = RobotMap.driveSubsystemRearRightEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    BetterGyro steeringGyro = RobotMap.driveSubsystemSteeringGyro;
    TempSensor steeringGyroTemp = RobotMap.driveSubsystemSteeringGyroTemp;
    ADXL345_I2C accelerometer = RobotMap.driveSubsystemAccelerometer;
    private BestRobotDrive robotDrive;

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new FieldCentricMecanumDriveCommand());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        robotDrive = new BestRobotDrive(frontLeftJaguar, rearLeftJaguar, frontRightJaguar, rearRightJaguar);
        robotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        robotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        steeringGyro.setPIDSourceParameter(PIDSource.PIDSourceParameter.kAngle);
    }

    public BestRobotDrive getRobotDrive() {
        return robotDrive;
    }
}
