// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2084.CMonster2014.subsystems;

import org.usfirst.frc2084.CMonster2014.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class LedSubsystem extends Subsystem {

    public static final int DISABLE_CODE = 0x3F;
    public static final int SOLID_GREEN_CODE = 0x0;
    public static final int SOLID_RED_CODE = 0x1;
    public static final int SOLID_BLUE_CODE = 0x2;
    public static final int BLINK_RED_CODE = 0x3;
    public static final int BLINK_BLUE_CODE = 0x4;
    public static final int BLINK_GREEN_CODE = 0x5;
    public static final int PULSE_RED_CODE = 0x6;
    public static final int PULSE_BLUE_CODE = 0x7;
    public static final int PULSE_GREEN_CODE = 0x8;
    public static final int CONVERGE_RED_CODE = 0x9;
    public static final int CONVERGE_BLUE_CODE = 0xA;
    public static final int CONVERGE_GREEN_CODE = 0xB;
    public static final int DIVERGE_RED_CODE = 0xC;
    public static final int DIVERGE_BLUE_CODE = 0xD;
    public static final int DIVERGE_GREEN_CODE = 0xE;
    public static final int RANDOM_PATTERN_CODE = 0xF;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalOutput pin0 = RobotMap.ledSubsystemPin0;
    DigitalOutput pin1 = RobotMap.ledSubsystemPin1;
    DigitalOutput pin2 = RobotMap.ledSubsystemPin2;
    DigitalOutput pin3 = RobotMap.ledSubsystemPin3;
    DigitalOutput pin4 = RobotMap.ledSubsystemPin4;
    DigitalOutput pin5 = RobotMap.ledSubsystemPin5;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    public void sendCode(int code) {
        byte mask = 0x1;
        for (int i = 0; i < 6; i++) {
            DigitalOutput out;
            switch (i) {
                case 0:
                    out = pin0;
                    break;
                case 1:
                    out = pin1;
                    break;
                case 2:
                    out = pin2;
                    break;
                case 3:
                    out = pin3;
                    break;
                case 4:
                    out = pin4;
                    break;
                case 5:
                default:
                    out = pin5;
            }
            out.set((code & mask) == 1);
            mask <<= 1;
        }
    }
}
