package org.usfirst.frc2084.CMonster2014.subsystems;
import org.usfirst.frc2084.CMonster2014.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class SweeperSubsystem extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Solenoid solenoid = RobotMap.sweeperSubsystemSolenoid;
    SpeedController jaguar = RobotMap.sweeperSubsystemJaguar;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public final double MOTOR_SPEED = 0.75;
    private MotorState state = MotorState.OFF;
    public static class MotorState {
        private final int state;
        private MotorState(int state) {
            this.state = state;
        }
        public static final MotorState SWEEPING = new MotorState(0);
        public static final MotorState OFF = new MotorState(1);
        public static final MotorState EJECTING = new MotorState(2);
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    public void extend() {
        if (!solenoid.get()) {
            solenoid.set(true);
        }
    }
    public void retract() {
        if (solenoid.get()) {
            solenoid.set(false);
        }
    }
    public void sweep() {
        jaguar.set(MOTOR_SPEED);
        state = MotorState.SWEEPING;
    }
    public void off() {
        jaguar.set(0);
        state = MotorState.OFF;
    }
    public void eject() {
        jaguar.set(-MOTOR_SPEED);
        state = MotorState.EJECTING;
    }
    public MotorState getState() {
        return state;
    }
}
