/* 
 * Copyright (c) 2015 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc.team2084.CMonster2015;

import org.usfirst.frc.team2084.CMonster2015.commands.ArcadeDriveCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.ClearFaultsCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.CloseToteGateCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.DriveToLocationCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.ExtendToteEjectorCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.FieldCentricMecanumDriveCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.LowerContainerHookCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.LowerToteLifterCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.OpenToteGateCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.RaiseContainerHookCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.RaiseToteLifterCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.ResetGyroCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.RetractToteEjectorCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.RotateToCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.SetHeadingCommand;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.buttons.NetworkButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton arcadeDriveButton;
    public JoystickButton fieldCentricMecanumDriveButton;
    public JoystickButton resetGyroButton;
    public Joystick driveJoystick;
    public JoystickButton raiseToteLifterButton;
    public JoystickButton lowerToteLifterButton;
    public JoystickButton extendToteEjectorButton;
    public JoystickButton retractToteEjectorButton;
    public Joystick secondaryJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public NetworkButton gyroEnableButton;

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        secondaryJoystick = new Joystick(1);

        retractToteEjectorButton = new JoystickButton(secondaryJoystick, 4);
        retractToteEjectorButton.whenPressed(new RetractToteEjectorCommand());
        extendToteEjectorButton = new JoystickButton(secondaryJoystick, 3);
        extendToteEjectorButton.whenPressed(new ExtendToteEjectorCommand());
        lowerToteLifterButton = new JoystickButton(secondaryJoystick, 2);
        lowerToteLifterButton.whenPressed(new LowerToteLifterCommand());
        raiseToteLifterButton = new JoystickButton(secondaryJoystick, 1);
        raiseToteLifterButton.whenPressed(new RaiseToteLifterCommand());
        driveJoystick = new Joystick(0);

        resetGyroButton = new JoystickButton(driveJoystick, 10);
        resetGyroButton.whenPressed(new ResetGyroCommand());
        fieldCentricMecanumDriveButton = new JoystickButton(driveJoystick, 8);
        fieldCentricMecanumDriveButton.whenPressed(new FieldCentricMecanumDriveCommand());
        arcadeDriveButton = new JoystickButton(driveJoystick, 7);
        arcadeDriveButton.whenPressed(new ArcadeDriveCommand());

        // SmartDashboard Buttons
        SmartDashboard.putData("Reset Gyro Command", new ResetGyroCommand());

        SmartDashboard.putData("Rotate To Command", new RotateToCommand());

        SmartDashboard.putData("Drive To Location Command", new DriveToLocationCommand());

        SmartDashboard.putData("Raise Tote Lifter Command", new RaiseToteLifterCommand());

        SmartDashboard.putData("Lower Tote Lifter Command", new LowerToteLifterCommand());

        SmartDashboard.putData("Extend Tote Ejector Command", new ExtendToteEjectorCommand());

        SmartDashboard.putData("Retract Tote Ejector Command", new RetractToteEjectorCommand());

        SmartDashboard.putData("Raise Container Hook Command", new RaiseContainerHookCommand());

        SmartDashboard.putData("Lower Container Hook Command", new LowerContainerHookCommand());

        SmartDashboard.putData("Open Tote Gate Command", new OpenToteGateCommand());

        SmartDashboard.putData("Close Tote Gate Command", new CloseToteGateCommand());

        SmartDashboard.putData("Set Heading Command", new SetHeadingCommand());

        SmartDashboard.putData("Clear Faults Command", new ClearFaultsCommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriveJoystick() {
        return driveJoystick;
    }

    public Joystick getSecondaryJoystick() {
        return secondaryJoystick;
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}
