/* 
 * Copyright (c) 2015 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc.team2084.CMonster2015;

import org.usfirst.frc.team2084.CMonster2015.commands.ArcadeDriveCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.DriveToLocationCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.FieldCentricMecanumDriveCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.GyroLoggingCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.LowerContainerHookCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.LowerToteLifterCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.RaiseContainerHookCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.RaiseToteLifterCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.ResetGyroCommand;
import org.usfirst.frc.team2084.CMonster2015.commands.RotateToCommand;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.buttons.NetworkButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton arcadeDriveButton;
    public JoystickButton fieldCentricMecanumDriveButton;
    public JoystickButton resetGyroButton;
    public Joystick driveJoystick;
    public Joystick secondaryJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public NetworkButton gyroEnableButton;

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        secondaryJoystick = new Joystick(1);

        driveJoystick = new Joystick(0);

        resetGyroButton = new JoystickButton(driveJoystick, 12);
        resetGyroButton.whenPressed(new ResetGyroCommand());
        fieldCentricMecanumDriveButton = new JoystickButton(driveJoystick, 8);
        fieldCentricMecanumDriveButton.whenPressed(new FieldCentricMecanumDriveCommand());
        arcadeDriveButton = new JoystickButton(driveJoystick, 7);
        arcadeDriveButton.whenPressed(new ArcadeDriveCommand());

        // SmartDashboard Buttons
        SmartDashboard.putData("Reset Gyro Command", new ResetGyroCommand());

        SmartDashboard.putData("Rotate To Command", new RotateToCommand());

        SmartDashboard.putData("Gyro Logging Command", new GyroLoggingCommand());

        SmartDashboard.putData("Drive To Location Command", new DriveToLocationCommand());

        SmartDashboard.putData("Raise Tote Lifter Command", new RaiseToteLifterCommand());

        SmartDashboard.putData("Lower Tote Lifter Command", new LowerToteLifterCommand());

        SmartDashboard.putData("Raise Container Hook Command", new RaiseContainerHookCommand());

        SmartDashboard.putData("Lower Container Hook Command", new LowerContainerHookCommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriveJoystick() {
        return driveJoystick;
    }

    public Joystick getSecondaryJoystick() {
        return secondaryJoystick;
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}
