// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team2084.CMonster2015.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class FeederStationDriveCommandGroup extends CommandGroup {

    public static final double LEFT_FEEDER_STATION_HEADING = Math.PI / 4;
    public static final double RIGHT_FEEDER_STATION_HEADING = -Math.PI / 4;

    public FeederStationDriveCommandGroup(boolean left) {
        addSequential(new RotateToCommand(left ? LEFT_FEEDER_STATION_HEADING : RIGHT_FEEDER_STATION_HEADING, 0.1, 4.0));
    }
}
