/* 
 * Copyright (c) 2015 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc.team2084.CMonster2015.commands;

import org.usfirst.frc.team2084.CMonster2015.Robot;
import org.usfirst.frc.team2084.CMonster2015.subsystems.ToteLifterSubsystem.LifterState;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class LowerToteLifterCommand extends Command {

    public static final double STORE_TIME = 0.5;

    public LowerToteLifterCommand() {
        super(2);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.toteLifterSubsystem);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    @Override
    protected void initialize() {
        Robot.toteLifterSubsystem.setLifterState(LifterState.STORE);
    }

    @Override
    protected void execute() {
        if (timeSinceInitialized() > STORE_TIME) {
            Robot.toteLifterSubsystem.setLifterState(LifterState.LOWER);
        }
    }

    @Override
    protected boolean isFinished() {
        return isTimedOut();
    }

    @Override
    protected void interrupted() {
    }

    @Override
    protected void end() {
    }

}
