/* 
 * Copyright (c) 2015 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc.team2084.CMonster2015.commands;

import org.usfirst.frc.team2084.CMonster2015.Robot;
import org.usfirst.frc.team2084.CMonster2015.subsystems.ToteLifterSubsystem.EjectorState;
import org.usfirst.frc.team2084.CMonster2015.subsystems.ToteLifterSubsystem.GateState;

import edu.wpi.first.wpilibj.command.Command;

/**
 * Retracts the tote ejector and raises closes the tote gate.
 */
public class RetractToteEjectorCommand extends Command {

    public RetractToteEjectorCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.toteLifterSubsystem);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    @Override
    protected void initialize() {
    }

    /**
     * Retracts the tote ejector.
     */
    @Override
    protected void execute() {
        Robot.toteLifterSubsystem.setEjectorState(EjectorState.RETRACTING, 1.0);
    }

    /**
     * Originally was going to use a limit switch, but this was not done, so
     * this always returns false.
     * 
     * @return false
     */
    @Override
    protected boolean isFinished() {
        return Robot.toteLifterSubsystem.isEjectorRetracted();
    }

    /**
     * Stops the tote ejector and closes the tote gate.
     */
    @Override
    protected void end() {
        Robot.toteLifterSubsystem.setGateState(GateState.CLOSED);
        Robot.toteLifterSubsystem.setEjectorState(EjectorState.STOPPED, 0.0);
    }

    @Override
    protected void interrupted() {
        end();
    }
}
