/* 
 * Copyright (c) 2015 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc.team2084.CMonster2015.commands;

import org.usfirst.frc.team2084.CMonster2015.RobotMap;

/**
 * Sets the heading of the robot to the certain value. This is useful during
 * autonomous if we do not start facing forward.
 */
public class SetHeadingCommand extends ParameterCommand {

    public static final String HEADING_KEY = "Heading";

    /**
     * Creates a new {@link SetHeadingCommand} that sets the heading to zero.
     */
    public SetHeadingCommand() {
        this(0);
    }

    /**
     * Creates a new {@link SetHeadingCommand} that sets the heading to the
     * specified value.
     * 
     * @param heading the heading to set
     */
    public SetHeadingCommand(double heading) {
        setRunWhenDisabled(true);
        addNumberParameter(HEADING_KEY, heading);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    /**
     * Sets the heading to the specified value.
     */
    @Override
    protected void initialize() {
        RobotMap.driveSubsystemMecanumDriveAlgorithm.setHeading(getNumberParameter(HEADING_KEY));
    }

    @Override
    protected void execute() {
    }

    /**
     * @return true
     */
    @Override
    protected boolean isFinished() {
        return true;
    }

    @Override
    protected void end() {
    }

    @Override
    protected void interrupted() {
    }
}
