/* 
 * Copyright (c) 2015 RobotsByTheC. All rights reserved.
 *
 * Open Source Software - may be modified and shared by FRC teams. The code must
 * be accompanied by the BSD license file in the root directory of the project.
 */
package org.usfirst.frc.team2084.CMonster2015.commands;

import org.usfirst.frc.team2084.CMonster2015.Robot;
import org.usfirst.frc.team2084.CMonster2015.subsystems.ContainerHookSubsystem.State;

import edu.wpi.first.wpilibj.command.Command;

/**
 * Lower the container hook. This does not have any way to stop automatically
 * because there is usually no need to lower it.
 */
public class LowerContainerHookCommand extends Command {

    public LowerContainerHookCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.containerHookSubsystem);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    @Override
    protected void initialize() {
    }

    /**
     * Lowers the container hook.
     */
    @Override
    protected void execute() {
        Robot.containerHookSubsystem.setState(State.LOWERING);
    }

    /**
     * This command never finishes because it is controlled with a button.
     * 
     * @return false
     */
    @Override
    protected boolean isFinished() {
        return false;
    }

    /**
     * Stops the container hook.
     */
    @Override
    protected void end() {
        Robot.containerHookSubsystem.setState(State.STOPPED);
    }

    /**
     * Stops the container hook.
     */
    @Override
    protected void interrupted() {
        end();
    }
}
